### ISSUE TITLE
Fail to run `azd up`

### ISSUE THREAD

**Issue by NanaXiong00** [marnixcox/logicapp-standard-func#2]
**Describe the issue:**
When running `azd up`, the following error occurs:
![image](https://github.com/user-attachments/assets/56290d53-ea2f-490f-879c-49dc000089be)

**Repro Steps:**
1. Run `azd auth login`
2. Run `azd init -t https://github.com/marnixcox/logicapp-standard-func`
3. Run `azd up`

**Environment:**
- azd version 1.10.3 (commit 0595f33fe948ee6df3da492567e3e7943cb9a733)
- OS: Windows

**Expected behavior:**
Run `azd up` can successfully.

@hemarina and @marnixcox  for notification.

**Comment by NanaXiong00** [comment]
@marnixcox Based on the latest code test, the above issue no longer occurs, but a new issue has appeared, as follows:
![image](https://github.com/user-attachments/assets/5e7c2e68-9ffe-4e42-aaca-89b5940ad141)

**Comment by marnixcox** [comment]
@NanaXiong00 Thanks for testing, I have now updated the prerequisites instruction

![image](https://github.com/user-attachments/assets/302d2c91-d2c6-4e91-9e1a-32414c2d3af1)

**Comment by NanaXiong00** [comment]
@marnixcox  Thanks for your reply, retested based on your comments and no such issue. The issue is now closed.
